// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/rekv.proto

package rekvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcCallRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Method string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path   string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// JSON-encoded ConfigValue envelope; empty for methods without a value.
	JsonValue     string `protobuf:"bytes,4,opt,name=json_value,json=jsonValue,proto3" json:"json_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcCallRequest) Reset() {
	*x = RpcCallRequest{}
	mi := &file_proto_rekv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCallRequest) ProtoMessage() {}

func (x *RpcCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCallRequest.ProtoReflect.Descriptor instead.
func (*RpcCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{0}
}

func (x *RpcCallRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RpcCallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RpcCallRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RpcCallRequest) GetJsonValue() string {
	if x != nil {
		return x.JsonValue
	}
	return ""
}

type RpcCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok    bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// JSON-encoded typed result.
	ResultJson    string `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ErrorCode     string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcCallResponse) Reset() {
	*x = RpcCallResponse{}
	mi := &file_proto_rekv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCallResponse) ProtoMessage() {}

func (x *RpcCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCallResponse.ProtoReflect.Descriptor instead.
func (*RpcCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{1}
}

func (x *RpcCallResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RpcCallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RpcCallResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *RpcCallResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RpcCallResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_rekv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	JsonValue     string                 `protobuf:"bytes,2,opt,name=json_value,json=jsonValue,proto3" json:"json_value,omitempty"`
	MatchCount    uint32                 `protobuf:"varint,3,opt,name=match_count,json=matchCount,proto3" json:"match_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_rekv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetJsonValue() string {
	if x != nil {
		return x.JsonValue
	}
	return ""
}

func (x *GetResponse) GetMatchCount() uint32 {
	if x != nil {
		return x.MatchCount
	}
	return 0
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	JsonValue     string                 `protobuf:"bytes,2,opt,name=json_value,json=jsonValue,proto3" json:"json_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_rekv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{4}
}

func (x *SetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetRequest) GetJsonValue() string {
	if x != nil {
		return x.JsonValue
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	AffectedCount uint32                 `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"`
	AffectedPaths []string               `protobuf:"bytes,4,rep,name=affected_paths,json=affectedPaths,proto3" json:"affected_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_rekv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{5}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SetResponse) GetAffectedCount() uint32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

func (x *SetResponse) GetAffectedPaths() []string {
	if x != nil {
		return x.AffectedPaths
	}
	return nil
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_rekv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{6}
}

func (x *WatchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type WatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OldValue      string                 `protobuf:"bytes,2,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      string                 `protobuf:"bytes,3,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	TimestampMs   uint64                 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_proto_rekv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rekv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_rekv_proto_rawDescGZIP(), []int{7}
}

func (x *WatchEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WatchEvent) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *WatchEvent) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *WatchEvent) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

var File_proto_rekv_proto protoreflect.FileDescriptor

const file_proto_rekv_proto_rawDesc = "" +
	"\n" +
	"\x10proto/rekv.proto\x12\x04rekv\"k\n" +
	"\x0eRpcCallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"json_value\x18\x04 \x01(\tR\tjsonValue\"\x96\x01\n" +
	"\x0fRpcCallResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1f\n" +
	"\vresult_json\x18\x03 \x01(\tR\n" +
	"resultJson\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"c\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1d\n" +
	"\n" +
	"json_value\x18\x02 \x01(\tR\tjsonValue\x12\x1f\n" +
	"\vmatch_count\x18\x03 \x01(\rR\n" +
	"matchCount\"?\n" +
	"\n" +
	"SetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"json_value\x18\x02 \x01(\tR\tjsonValue\"\x8b\x01\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\rR\raffectedCount\x12%\n" +
	"\x0eaffected_paths\x18\x04 \x03(\tR\raffectedPaths\"\"\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"}\n" +
	"\n" +
	"WatchEvent\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\told_value\x18\x02 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x03 \x01(\tR\bnewValue\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x04R\vtimestampMs2\xcb\x01\n" +
	"\vRekvService\x123\n" +
	"\x04Call\x12\x14.rekv.RpcCallRequest\x1a\x15.rekv.RpcCallResponse\x12*\n" +
	"\x03Get\x12\x10.rekv.GetRequest\x1a\x11.rekv.GetResponse\x12*\n" +
	"\x03Set\x12\x10.rekv.SetRequest\x1a\x11.rekv.SetResponse\x12/\n" +
	"\x05Watch\x12\x12.rekv.WatchRequest\x1a\x10.rekv.WatchEvent0\x01B.Z,github.com/raut/rekv/clients/go/proto;rekvpbb\x06proto3"

var (
	file_proto_rekv_proto_rawDescOnce sync.Once
	file_proto_rekv_proto_rawDescData []byte
)

func file_proto_rekv_proto_rawDescGZIP() []byte {
	file_proto_rekv_proto_rawDescOnce.Do(func() {
		file_proto_rekv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rekv_proto_rawDesc), len(file_proto_rekv_proto_rawDesc)))
	})
	return file_proto_rekv_proto_rawDescData
}

var file_proto_rekv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_rekv_proto_goTypes = []any{
	(*RpcCallRequest)(nil),  // 0: rekv.RpcCallRequest
	(*RpcCallResponse)(nil), // 1: rekv.RpcCallResponse
	(*GetRequest)(nil),      // 2: rekv.GetRequest
	(*GetResponse)(nil),     // 3: rekv.GetResponse
	(*SetRequest)(nil),      // 4: rekv.SetRequest
	(*SetResponse)(nil),     // 5: rekv.SetResponse
	(*WatchRequest)(nil),    // 6: rekv.WatchRequest
	(*WatchEvent)(nil),      // 7: rekv.WatchEvent
}
var file_proto_rekv_proto_depIdxs = []int32{
	0, // 0: rekv.RekvService.Call:input_type -> rekv.RpcCallRequest
	2, // 1: rekv.RekvService.Get:input_type -> rekv.GetRequest
	4, // 2: rekv.RekvService.Set:input_type -> rekv.SetRequest
	6, // 3: rekv.RekvService.Watch:input_type -> rekv.WatchRequest
	1, // 4: rekv.RekvService.Call:output_type -> rekv.RpcCallResponse
	3, // 5: rekv.RekvService.Get:output_type -> rekv.GetResponse
	5, // 6: rekv.RekvService.Set:output_type -> rekv.SetResponse
	7, // 7: rekv.RekvService.Watch:output_type -> rekv.WatchEvent
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rekv_proto_init() }
func file_proto_rekv_proto_init() {
	if File_proto_rekv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rekv_proto_rawDesc), len(file_proto_rekv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rekv_proto_goTypes,
		DependencyIndexes: file_proto_rekv_proto_depIdxs,
		MessageInfos:      file_proto_rekv_proto_msgTypes,
	}.Build()
	File_proto_rekv_proto = out.File
	file_proto_rekv_proto_goTypes = nil
	file_proto_rekv_proto_depIdxs = nil
}
