// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/rekv.proto

package rekvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RekvService_Call_FullMethodName  = "/rekv.RekvService/Call"
	RekvService_Get_FullMethodName   = "/rekv.RekvService/Get"
	RekvService_Set_FullMethodName   = "/rekv.RekvService/Set"
	RekvService_Watch_FullMethodName = "/rekv.RekvService/Watch"
)

// RekvServiceClient is the client API for RekvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RekvServiceClient interface {
	// Runtime-typed CRUD operation used by language clients.
	Call(ctx context.Context, in *RpcCallRequest, opts ...grpc.CallOption) (*RpcCallResponse, error)
	// Query configuration by XPath-like path
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Set configuration value at an XPath-like path
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	// Watch for configuration changes at an XPath-like path in real-time
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error)
}

type rekvServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRekvServiceClient(cc grpc.ClientConnInterface) RekvServiceClient {
	return &rekvServiceClient{cc}
}

func (c *rekvServiceClient) Call(ctx context.Context, in *RpcCallRequest, opts ...grpc.CallOption) (*RpcCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RpcCallResponse)
	err := c.cc.Invoke(ctx, RekvService_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rekvServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RekvService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rekvServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, RekvService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rekvServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RekvService_ServiceDesc.Streams[0], RekvService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RekvService_WatchClient = grpc.ServerStreamingClient[WatchEvent]

// RekvServiceServer is the server API for RekvService service.
// All implementations must embed UnimplementedRekvServiceServer
// for forward compatibility.
type RekvServiceServer interface {
	// Runtime-typed CRUD operation used by language clients.
	Call(context.Context, *RpcCallRequest) (*RpcCallResponse, error)
	// Query configuration by XPath-like path
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Set configuration value at an XPath-like path
	Set(context.Context, *SetRequest) (*SetResponse, error)
	// Watch for configuration changes at an XPath-like path in real-time
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error
	mustEmbedUnimplementedRekvServiceServer()
}

// UnimplementedRekvServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRekvServiceServer struct{}

func (UnimplementedRekvServiceServer) Call(context.Context, *RpcCallRequest) (*RpcCallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedRekvServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRekvServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedRekvServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedRekvServiceServer) mustEmbedUnimplementedRekvServiceServer() {}
func (UnimplementedRekvServiceServer) testEmbeddedByValue()                     {}

// UnsafeRekvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RekvServiceServer will
// result in compilation errors.
type UnsafeRekvServiceServer interface {
	mustEmbedUnimplementedRekvServiceServer()
}

func RegisterRekvServiceServer(s grpc.ServiceRegistrar, srv RekvServiceServer) {
	// If the following call pancis, it indicates UnimplementedRekvServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RekvService_ServiceDesc, srv)
}

func _RekvService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RekvServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RekvService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RekvServiceServer).Call(ctx, req.(*RpcCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RekvService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RekvServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RekvService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RekvServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RekvService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RekvServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RekvService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RekvServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RekvService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RekvServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RekvService_WatchServer = grpc.ServerStreamingServer[WatchEvent]

// RekvService_ServiceDesc is the grpc.ServiceDesc for RekvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RekvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rekv.RekvService",
	HandlerType: (*RekvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _RekvService_Call_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RekvService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _RekvService_Set_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _RekvService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rekv.proto",
}
